psd_friends_homepage:
    path:     /
    defaults: { _controller: PsdFriendsBundle:Login:login }
    
psd_friends_login:
    path:   /login
    defaults: { _controller: PsdFriendsBundle:Login:login}

time_line:
    path:     /timeLine
    defaults: { _controller: PsdFriendsBundle:Timeline:timeLine }
